#Brian Ackley
#Assignment 3
#file: makefile
#description: the makefile, which compiles all the files at once

Main: Main.o Person.o Student.o Employee.o Faculty.o Staff.o StaffST.o
	g++ Main.o Person.o Student.o Employee.o Faculty.o Staff.o StaffST.o -o Main
Main.o: Main.cpp
	g++ -c Main.cpp
Person.o: Person.cpp
	g++ -c Person.cpp
Student.o: Student.cpp
	g++ -c Student.cpp
Employee.o: Employee.cpp
	g++ -c Employee.cpp
Faculty.o: Faculty.cpp
	g++ -c Faculty.cpp
Staff.o: Staff.cpp
	g++ -c Faculty.cpp
StaffST.o: StaffST.cpp
	g++ -c StaffST.cpp
