main: main.o userpw.o passwordfile.o
	g++ main.o userpw.o passwordfile.o -o main

main.o: main.cpp
	g++ -c main.cpp

userpw.o: userpw.cpp
	g++ -c userpw.cpp

passwordfile.o: passwordfile.cpp
	g++ -c passwordfile.cpp
