(define (maxmin a)
   (if (null a)
       (list NIL NIL)
       (let* ( (mm (maxmin (cdr a)))
               (olmax (car mm))
               (olmin (cadr mm))
               (numax (if (null olmax) (car a) (max (car a) olmax)))
               (numin (if (null olmin) (car a) (min (car a) olmin)))
             )
             (list numax numin)
       )
    )
)
